language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services:
  - mysql2
before_install:
  - mysql2 -e 'CREATE DATABASE IF NOT EXISTS exchangestuffdb;'
